'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("simple_3d_engine.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ####
        '''#
        '''#	OBJ File Generated by LightWave3D
        '''#	LightWave3D OBJ Export v2.3
        '''#
        '''####
        '''o logo.obj
        '''mtllib logo.mtl
        '''g default
        '''v -4.782 0.08 -4.3
        '''v -4.782 0.08 -4.6
        '''v -4.78165 0.075769 -4.3
        '''v -4.78165 0.075769 -4.6
        '''v -4.78128 0.08864 -4.3
        '''v -4.78128 0.08864 -4.6
        '''v -4.78067 0.0720891 -4.3
        '''v -4.78067 0.0720891 -4.6
        '''v -4.77913 0.0687901 -4.3
        '''v -4.77913 0.0687901 -4.6
        '''v -4.77912 0.10016 -4.3
        '''v -4.77912 0.10016 -4.6
        '''v -4.77692 0.0656653 -4.3
        '''v -4.77692 0.0656653 -4.6
        '''v -4.77552 0.11456 -4.3
        '''v -4.77 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property logo() As String
            Get
                Return ResourceManager.GetString("logo", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
